services:
  front:
    depends_on:
      server:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_DATABASE_URL: ${VITE_FIREBASE_DATABASE_URL}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGE_SENDER_ID: ${VITE_FIREBASE_MESSAGE_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_FIREBASE_MESUREMENT_ID: ${VITE_FIREBASE_MESUREMENT_ID}
      VITE_GEOAPPIFY_API_KEY: ${VITE_GEOAPPIFY_API_KEY}
    ports:
      - "5173:5173"
    volumes:
      - ./front/node_modules:/usr/app/node_modules
    networks:
      - front
      - server

  server:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    environment:
      PORT: 5001
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    ports:
      # Firebase Functions emulator
      - "${PORT:-5001}:5001"
      # Firebase Emulator Suite UI
      - "4000:4000"
      # Firebase Auth emulator
      - "9099:9099"
      # Firebase Firestore emulator
      - "8080:8080"
      # Firebase Realtime Database emulator
      - "9000:9000"
      # Firebase Storage emulator
      - "9199:9199"
      # Firebase Hosting emulator
      - "5000:5000"
      # Firebase Pub/Sub emulator
      - "8085:8085"
    volumes:
      - ./server/node_modules:/usr/app/node_modules
      - ./firebase-service-account.json:/usr/app/firebase-service-account.json:ro
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:5001/admin-1000-moustaches/us-central1/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - server

  database:
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - server
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-P",
          "${DB_PORT:-3306}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  # The presence of these objects is sufficient to define them
  front: {}
  server: {}
