import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1738944921363 implements MigrationInterface {
    name = 'Init1738944921363'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`host_family_kind\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`species\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`veterinarian\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL DEFAULT NULL, \`mail\` varchar(255) NULL DEFAULT NULL, \`emergencies\` varchar(255) NULL DEFAULT NULL, \`appointmentConfirmationProcedure\` varchar(255) NULL DEFAULT NULL, \`invoicePaymentDate\` varchar(255) NULL DEFAULT NULL, \`paymentMethod\` varchar(255) NULL DEFAULT NULL, \`address\` varchar(255) NULL DEFAULT NULL, \`latitude\` int NULL DEFAULT NULL, \`longitude\` int NULL DEFAULT NULL, \`priceLevel\` int NULL DEFAULT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`veterinarian_intervention\` (\`id\` int NOT NULL AUTO_INCREMENT, \`date\` datetime NOT NULL, \`description\` varchar(255) NULL DEFAULT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`veterinarianId\` int NULL, \`animalId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`animal\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`icad\` varchar(255) NOT NULL, \`sexe\` varchar(255) NULL DEFAULT NULL, \`race\` varchar(255) NULL DEFAULT NULL, \`birthdate\` datetime NULL DEFAULT NULL, \`entryDate\` datetime NULL DEFAULT NULL, \`distinctiveSigns\` varchar(255) NULL DEFAULT NULL, \`reasonForCare\` varchar(255) NULL DEFAULT NULL, \`placeOfCare\` varchar(255) NULL DEFAULT NULL, \`careInfos\` varchar(255) NULL DEFAULT NULL, \`exitDate\` datetime NULL DEFAULT NULL, \`exitReason\` varchar(255) NULL DEFAULT NULL, \`exitInfos\` varchar(255) NULL DEFAULT NULL, \`deathDate\` datetime NULL DEFAULT NULL, \`deathReason\` varchar(255) NULL DEFAULT NULL, \`sterilised\` tinyint NULL DEFAULT NULL, \`firstVaccinationDate\` datetime NULL DEFAULT NULL, \`secondVaccinationDate\` datetime NULL DEFAULT NULL, \`fivNegative\` tinyint NULL DEFAULT NULL, \`felvNegative\` tinyint NULL DEFAULT NULL, \`healthIssues\` varchar(255) NULL DEFAULT NULL, \`behaviour\` varchar(255) NULL DEFAULT NULL, \`needFriends\` tinyint NULL DEFAULT NULL, \`posture\` varchar(255) NULL DEFAULT NULL, \`catsOk\` tinyint NULL DEFAULT NULL, \`dogsOk\` tinyint NULL DEFAULT NULL, \`kidsOk\` tinyint NULL DEFAULT NULL, \`behaviorParticularity\` varchar(255) NULL DEFAULT NULL, \`adopted\` tinyint NULL DEFAULT NULL, \`broadcastable\` tinyint NULL DEFAULT NULL, \`bookable\` tinyint NULL DEFAULT NULL, \`needExternalAccess\` tinyint NULL DEFAULT NULL, \`transferor\` varchar(255) NULL DEFAULT NULL, \`antiParasiticDate\` datetime NULL DEFAULT NULL, \`transferCertificate\` tinyint NULL DEFAULT NULL, \`reserved\` tinyint NULL DEFAULT NULL, \`needIcadDuplicate\` varchar(255) NULL DEFAULT NULL, \`contractSent\` tinyint NULL DEFAULT NULL, \`albumCreated\` tinyint NULL DEFAULT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`speciesId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`animals_to_host_families\` (\`id\` int NOT NULL AUTO_INCREMENT, \`entryDate\` timestamp NULL DEFAULT NULL, \`animalId\` int NULL, \`hostFamilyId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`host_family\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`firstname\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL DEFAULT NULL, \`mail\` varchar(255) NULL DEFAULT NULL, \`socialNetworkAlias\` varchar(255) NULL DEFAULT NULL, \`address\` varchar(255) NULL DEFAULT NULL, \`latitude\` int NULL DEFAULT NULL, \`longitude\` int NULL DEFAULT NULL, \`driverLicense\` tinyint NULL DEFAULT NULL, \`hasVehicule\` tinyint NULL DEFAULT NULL, \`nbChildren\` int NULL DEFAULT NULL, \`childrenInfos\` varchar(255) NULL DEFAULT NULL, \`animalsInfos\` varchar(255) NULL DEFAULT NULL, \`canProvideVeterinaryCare\` tinyint NULL DEFAULT NULL, \`canProvideSociabilisation\` tinyint NULL DEFAULT NULL, \`canHostDisableAnimal\` tinyint NULL DEFAULT NULL, \`canProvideNightCare\` tinyint NULL DEFAULT NULL, \`observations\` varchar(255) NULL DEFAULT NULL, \`housingInformations\` varchar(255) NULL DEFAULT NULL, \`canIsolate\` varchar(255) NULL DEFAULT NULL, \`hostConditions\` varchar(255) NULL DEFAULT NULL, \`onBreak\` tinyint NULL DEFAULT FALSE, \`membershipUpToDate\` tinyint NULL DEFAULT FALSE, \`isTemporary\` tinyint NULL DEFAULT FALSE, \`situation\` varchar(255) NULL DEFAULT NULL, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`referentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NULL DEFAULT NULL, \`firstname\` varchar(255) NULL DEFAULT NULL, \`email\` varchar(255) NULL DEFAULT NULL, \`isReferent\` tinyint NULL DEFAULT FALSE, \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`host_family_host_family_kinds_host_family_kind\` (\`hostFamilyId\` int NOT NULL, \`hostFamilyKindId\` int NOT NULL, INDEX \`IDX_1f43715f1c9965d27233769203\` (\`hostFamilyId\`), INDEX \`IDX_285c962356128eb4020a424602\` (\`hostFamilyKindId\`), PRIMARY KEY (\`hostFamilyId\`, \`hostFamilyKindId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`veterinarian_intervention\` ADD CONSTRAINT \`FK_6ad4b879eeb6ba4380176ab1965\` FOREIGN KEY (\`veterinarianId\`) REFERENCES \`veterinarian\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`veterinarian_intervention\` ADD CONSTRAINT \`FK_66e2672d753bc6fe32d247b85ee\` FOREIGN KEY (\`animalId\`) REFERENCES \`animal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`animal\` ADD CONSTRAINT \`FK_3ea91e9bbecafc1d0093ee48e89\` FOREIGN KEY (\`speciesId\`) REFERENCES \`species\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`animals_to_host_families\` ADD CONSTRAINT \`FK_58f36bdb0c809bb6c7d768e3bf8\` FOREIGN KEY (\`animalId\`) REFERENCES \`animal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`animals_to_host_families\` ADD CONSTRAINT \`FK_cd86b3b3afe38019ac72cc9c2d8\` FOREIGN KEY (\`hostFamilyId\`) REFERENCES \`host_family\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_family\` ADD CONSTRAINT \`FK_ba340d3cca120024aa00b03db32\` FOREIGN KEY (\`referentId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`host_family_host_family_kinds_host_family_kind\` ADD CONSTRAINT \`FK_1f43715f1c9965d272337692034\` FOREIGN KEY (\`hostFamilyId\`) REFERENCES \`host_family\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`host_family_host_family_kinds_host_family_kind\` ADD CONSTRAINT \`FK_285c962356128eb4020a424602d\` FOREIGN KEY (\`hostFamilyKindId\`) REFERENCES \`host_family_kind\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
                        
        // Add Default Species (Chat, Chien)
        await queryRunner.query(`INSERT INTO \`species\` (\`id\`, \`name\`) VALUES (1, 'Chat'), (2, 'Chien')`);

        // Add Default Host Family Kind (Chats, Chats + Maman, Chiens, Chatons biberonnage, Chiots, Lapins, Chatons, Rats, Hamsters)
        await queryRunner.query(`INSERT INTO \`host_family_kind\` (\`id\`, \`name\`) VALUES (1, 'Chats'), (2, 'Chatons + Maman'), (3, 'Chiens'), (4, 'Chatons biberonnage'), (5, 'Chiots'), (6, 'Lapins'), (13, 'Chatons'), (14, 'Rats'), (15, 'Hamsters')`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`host_family_host_family_kinds_host_family_kind\` DROP FOREIGN KEY \`FK_285c962356128eb4020a424602d\``);
        await queryRunner.query(`ALTER TABLE \`host_family_host_family_kinds_host_family_kind\` DROP FOREIGN KEY \`FK_1f43715f1c9965d272337692034\``);
        await queryRunner.query(`ALTER TABLE \`host_family\` DROP FOREIGN KEY \`FK_ba340d3cca120024aa00b03db32\``);
        await queryRunner.query(`ALTER TABLE \`animals_to_host_families\` DROP FOREIGN KEY \`FK_cd86b3b3afe38019ac72cc9c2d8\``);
        await queryRunner.query(`ALTER TABLE \`animals_to_host_families\` DROP FOREIGN KEY \`FK_58f36bdb0c809bb6c7d768e3bf8\``);
        await queryRunner.query(`ALTER TABLE \`animal\` DROP FOREIGN KEY \`FK_3ea91e9bbecafc1d0093ee48e89\``);
        await queryRunner.query(`ALTER TABLE \`veterinarian_intervention\` DROP FOREIGN KEY \`FK_66e2672d753bc6fe32d247b85ee\``);
        await queryRunner.query(`ALTER TABLE \`veterinarian_intervention\` DROP FOREIGN KEY \`FK_6ad4b879eeb6ba4380176ab1965\``);
        await queryRunner.query(`DROP INDEX \`IDX_285c962356128eb4020a424602\` ON \`host_family_host_family_kinds_host_family_kind\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f43715f1c9965d27233769203\` ON \`host_family_host_family_kinds_host_family_kind\``);
        await queryRunner.query(`DROP TABLE \`host_family_host_family_kinds_host_family_kind\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`host_family\``);
        await queryRunner.query(`DROP TABLE \`animals_to_host_families\``);
        await queryRunner.query(`DROP TABLE \`animal\``);
        await queryRunner.query(`DROP TABLE \`veterinarian_intervention\``);
        await queryRunner.query(`DROP TABLE \`veterinarian\``);
        await queryRunner.query(`DROP TABLE \`species\``);
        await queryRunner.query(`DROP TABLE \`host_family_kind\``);
    }

}
